[package]
name = "splay-safe-rs"
version = "0.7.0-dev"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
compare = "0.1"

[dev-dependencies]
rand = "0.8"
