name: CI

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check std build
        run: cargo check
      - name: Check no_std build
        run: cargo check --no-default-features
